create table SMS_MA_BRANCH (id  bigserial not null, BR_CODE varchar(255) not null, BR_ACTIVE int4 not null, BR_NAME varchar(255) not null, BR_ADDRESS_ID int8 not null, primary key (id));
create table SMS_MA_COURSE (id  bigserial not null, CO_CODE varchar(255), CO_DESCRIPTION varchar(255), CO_NAME varchar(255), primary key (id));
create table SMS_MA_FEES_PARTICULAR (id  bigserial not null, FP_CODE varchar(255) not null, FP_NAME varchar(255) not null, primary key (id));
create table SMS_MA_ROLE_OPERATION_LINK (id  bigserial not null, ROL_SO_ID int8, ROL_UR_ID int8, primary key (id));
create table SMS_MA_SCHEME (id  bigserial not null, SC_CODE varchar(255), SC_DESCRIPTION varchar(255), SC_FEES_AMOUNT numeric(19, 2), SC_NAME varchar(255), primary key (id));
create table SMS_MA_SECURED_OPERATION (id  bigserial not null, SO_OPERATION varchar(255) not null, SO_OPERATION_DESC varchar(255) not null, SO_TYPE varchar(255) not null, primary key (id));
create table SMS_MA_USER (id  bigserial not null, US_BRANCH varchar(255), US_FIRST_NAME varchar(255), US_LAST_NAME varchar(255), US_NAME varchar(255), US_PASSWORD varchar(255), US_UR_ID int8, primary key (id));
create table SMS_MA_USER_ROLE (id  bigserial not null, UR_DESC varchar(255) not null, UR_NAME varchar(255) not null, primary key (id));
create table SMS_TR_ADDRESS (id  bigserial not null, AD_ADDRESS_1 varchar(255) not null, AD_ADDRESS_2 varchar(255), AD_ADDRESS_3 varchar(255), AD_DISTRICT varchar(255) not null, AD_POSTAL_CODE int8 check (AD_POSTAL_CODE<=999999 AND AD_POSTAL_CODE>=100000), AD_TALUK varchar(255) not null, primary key (id));
create table SMS_TR_EDUCATION_DETAIL (id  bigserial not null, ED_EXAM_PASSED varchar(255) not null, ED_GROUP_NAME varchar(255) not null, ED_INSTITUTE_NAME varchar(255) not null, ED_PASSING_YEAR int8 check (ED_PASSING_YEAR>=2000 AND ED_PASSING_YEAR<=2200), ED_PERCENTAGE_OBTAINED int4 check (ED_PERCENTAGE_OBTAINED>=1 AND ED_PERCENTAGE_OBTAINED<=100), ED_REMARK varchar(255), STS_ED_STUDENT_ID int8, ED_STUDENT_ID int8, primary key (id));
create table SMS_TR_GUARDIAN (id  bigserial not null, GU_NAME varchar(255) not null, GU_OCCUPATION varchar(255) not null, GU_PHONE_NUMBER varchar(13) not null, GU_RELATION int4 not null, GU_STUDENT_ID int8, primary key (id));
create table SMS_TR_ID_CARD (id  bigserial not null, IC_BRANCH_NAME varchar(255), IC_CREATED_DATE date, IC_FMS_ID int8, IC_IDENTITY_CODE varchar(255), IC_LAST_MODIFIED_DATE date, IC_NAME varchar(255), IC_STATUS varchar(255), IC_VALIDITY date, IC_ADDRESS_ID int8, primary key (id));
create table SMS_TR_MARKETING_EMPLOYEE (id  bigserial not null, ME_CODE varchar(255), ME_DESIGNATION int4, ME_NAME varchar(255), ME_PHONE_NUMBER varchar(255), ME_ADDRESS_ID int8, ME_USER_ID int8, primary key (id));
create table SMS_TR_MARK_DETAILS (CLASS varchar(31) not null, MD_ID int8 not null, MS_BOARD_OF_EXAMINATION varchar(255) not null, MS_PLACE_SCHOOL varchar(255) not null, MS_REG_NUMBER varchar(255) not null, MS_SCHOOL_NAME varchar(255) not null, MS_YEAR_PASSING int4 check (MS_YEAR_PASSING>=2000 AND MS_YEAR_PASSING<=2200), MD_PERCENTAGE int4 check (MD_PERCENTAGE>=1 AND MD_PERCENTAGE<=100), MD_TOTAL_MARKS int8 check (MD_TOTAL_MARKS>=1), primary key (MD_ID));
create table SMS_TR_OTHER_LANGUAGE (id int8 not null, OL_READ boolean, OL_SPEAK boolean, OL_WRITE boolean, OL_NAME varchar(255) not null, OL_STUDENT_ID int8, primary key (id));
create table SMS_TR_PAYMENT (id int8 not null, SP_ADMITTED_BY varchar(255), SP_ADMITTED_REJECTED_BY varchar(255), SP_AMOUNT numeric(19, 2), SP_APPROVED_BY varchar(255), SP_BANK_BRANCH_NAME varchar(255), SP_BANK_NAME varchar(255), SP_DD_NUMBER varchar(255), SP_PAID_DATE timestamp, SP_STUDENT_ID int8, primary key (id));
create table SMS_TR_PAYMENT_FEES (id  bigserial not null, FC_AMOUNT numeric(19, 2), FC_FEES_PARTICULAR_ID int8, SP_PAYMENT_ID int8, primary key (id));
create table SMS_TR_SCHEME_TO_FEES (id  bigserial not null, FC_AMOUNT numeric(19, 2), FC_FEES_PARTICULAR_ID int8, FC_SCHEME_ID int8, primary key (id));
create table SMS_TR_STUDENT (id  bigserial not null, ST_AGE int4, ST_ALTERNATE_PHONE_NUMBER varchar(255), ST_CASTE varchar(255), ST_CODE varchar(255), ST_CREATION_DATE timestamp, ST_DATE_OF_BIRTH timestamp, ST_ENGLISH_FLUENCY varchar(255), ST_FATHER_OR_MOTHER_NAME varchar(255), ST_FMS_PHOTO_ID int8, ST_GENDER varchar(255), ST_LAST_MODIFIED_DATE timestamp, ST_MAIL_ID varchar(255), ST_MARITAL_STATUS varchar(255), ST_NAME varchar(255), ST_NATIONALITY varchar(255), ST_PHONE_NUMBER varchar(255), ST_RELIGION varchar(255), ST_SCHOLAR_APP_NO varchar(255), ST_STATUS varchar(255), ST_ADDRESS_ID int8, ST_BRANCH_ID int8, ST_COURSE_ID int8, ST_MD_HSC_ID int8, ST_MARKETING_EMPLOYEE_ID int8, ST_SCHEME_ID int8, ST_MD_SSLC_ID int8, primary key (id));
create table SMS_TR_STUDENT_FEES (id  bigserial not null, FC_AMOUNT numeric(19, 2), FC_FEES_PARTICULAR_ID int8, SF_STUDENT_ID int8, primary key (id));
create table SMS_TR_STUDENT_SCHOLARSHIP (id  bigserial not null, STS_AGE int4, STS_ANNUAL_INCOME varchar(255), STS_APPLICATION_NUMBER varchar(255), STS_CASTE varchar(255), STS_CASTEDESCRIPTION varchar(255), STS_CREATION_DATE timestamp, STS_DATE_OF_BIRTH timestamp, STS_EMAILID varchar(255), STS_PARENT_NAME varchar(255), STS_GENDER varchar(255), STS_LAST_MODIFIED_DATE timestamp, STS_MARITAL_STATUS varchar(255), STS_NAME varchar(255), STS_NATIONALITY varchar(255), STS_PARENT_PHONE_NUMBER varchar(255), STS_RELIGION varchar(255), STS_STATUS varchar(255), STS_PHONE_NUMBER varchar(255), STS_ADDRESS_ID int8, STS_BRANCH_ID int8, STS_MARKETING_EMPLOYEE_ID int8, primary key (id));
create table SMS_TR_SUBJECT (id  bigserial not null, SU_NAME varchar(255) not null, SU_SECURED_MARK int8 check (SU_SECURED_MARK>=1), SU_TOTAL_MARK int8 check (SU_TOTAL_MARK>=1), SU_MD_ID int8, primary key (id));
alter table SMS_MA_BRANCH add constraint UK_BR_001 unique (BR_CODE);
alter table SMS_MA_COURSE add constraint UK_CR_001 unique (CO_CODE);
alter table SMS_MA_FEES_PARTICULAR add constraint UK_FP_001 unique (FP_CODE);
alter table SMS_MA_SCHEME add constraint UK_SC_001 unique (SC_CODE);
alter table SMS_MA_USER add constraint UK_US_001 unique (US_NAME);
alter table SMS_MA_USER_ROLE add constraint UK_UR_001 unique (UR_NAME);
alter table SMS_TR_MARKETING_EMPLOYEE add constraint UK_ME_001 unique (ME_CODE);
alter table SMS_TR_STUDENT add constraint UK_ST_001 unique (ST_CODE);
alter table SMS_TR_STUDENT add constraint UK_ST_002 unique (ST_MAIL_ID);
alter table SMS_TR_STUDENT add constraint UK_ST_003 unique (ST_MD_HSC_ID);
alter table SMS_TR_STUDENT add constraint UK_ST_004 unique (ST_MD_SSLC_ID);
alter table SMS_TR_STUDENT_SCHOLARSHIP add constraint UK_STS_001 unique (STS_APPLICATION_NUMBER);
alter table SMS_TR_STUDENT_SCHOLARSHIP add constraint UK_STS_001 unique (STS_EMAILID);
alter table SMS_MA_BRANCH add constraint FK_BR_001 foreign key (BR_ADDRESS_ID) references SMS_TR_ADDRESS;
alter table SMS_MA_USER add constraint FK_US_001 foreign key (US_UR_ID) references SMS_MA_USER_ROLE;
alter table SMS_TR_EDUCATION_DETAIL add constraint FK_ED_001 foreign key (STS_ED_STUDENT_ID) references SMS_TR_STUDENT_SCHOLARSHIP;
alter table SMS_TR_EDUCATION_DETAIL add constraint FK_ED_001 foreign key (ED_STUDENT_ID) references SMS_TR_STUDENT;
alter table SMS_TR_GUARDIAN add constraint FK_GD_001 foreign key (GU_STUDENT_ID) references SMS_TR_STUDENT;
alter table SMS_TR_ID_CARD add constraint FK_rv8ro6iysi505mv6d8335nd7h foreign key (IC_ADDRESS_ID) references SMS_TR_ADDRESS;
alter table SMS_TR_MARKETING_EMPLOYEE add constraint FK_j4iopm6dqxfdal8iy22h0er5r foreign key (ME_ADDRESS_ID) references SMS_TR_ADDRESS;
alter table SMS_TR_MARKETING_EMPLOYEE add constraint FK_emvf5vnqw7r5oyyet9247oxu3 foreign key (ME_USER_ID) references SMS_MA_USER;
alter table SMS_TR_OTHER_LANGUAGE add constraint FK_1ob746wy4e8rg16naqrkuaopl foreign key (OL_STUDENT_ID) references SMS_TR_STUDENT;
alter table SMS_TR_PAYMENT add constraint FK_nhpxhvb9u8x9ae16hvpflmcp4 foreign key (SP_STUDENT_ID) references SMS_TR_STUDENT;
alter table SMS_TR_PAYMENT_FEES add constraint FK_cd9bwuenkepfi5iwcv526gwkn foreign key (FC_FEES_PARTICULAR_ID) references SMS_MA_FEES_PARTICULAR;
alter table SMS_TR_PAYMENT_FEES add constraint FK_66becvjiuia7ymhubemftmbd foreign key (SP_PAYMENT_ID) references SMS_TR_PAYMENT;
alter table SMS_TR_SCHEME_TO_FEES add constraint FK_ew1b0tg9fe4r4rxy23f0lds4a foreign key (FC_FEES_PARTICULAR_ID) references SMS_MA_FEES_PARTICULAR;
alter table SMS_TR_SCHEME_TO_FEES add constraint FK_qal8cv88lwnu4bg3yfxn9mfcl foreign key (FC_SCHEME_ID) references SMS_MA_SCHEME;
alter table SMS_TR_STUDENT add constraint FK_46s3o1bvjdb33f5ha8kc8fm3i foreign key (ST_ADDRESS_ID) references SMS_TR_ADDRESS;
alter table SMS_TR_STUDENT add constraint FK_2jstqqpmpq2bwux56v17v3g2x foreign key (ST_BRANCH_ID) references SMS_MA_BRANCH;
alter table SMS_TR_STUDENT add constraint FK_82wh05qbl2vvi25bkqg8373pl foreign key (ST_COURSE_ID) references SMS_MA_COURSE;
alter table SMS_TR_STUDENT add constraint FK_nmk6ojvca4qfv2krvceg772y8 foreign key (ST_MD_HSC_ID) references SMS_TR_MARK_DETAILS;
alter table SMS_TR_STUDENT add constraint FK_bmdvyu9k01v6e73wyyf7j797o foreign key (ST_MARKETING_EMPLOYEE_ID) references SMS_TR_MARKETING_EMPLOYEE;
alter table SMS_TR_STUDENT add constraint FK_foteqp2h3r6lbagpdja7d0mja foreign key (ST_SCHEME_ID) references SMS_MA_SCHEME;
alter table SMS_TR_STUDENT add constraint FK_qdq1odhkk4jwfsy28rqgib33s foreign key (ST_MD_SSLC_ID) references SMS_TR_MARK_DETAILS;
alter table SMS_TR_STUDENT_FEES add constraint FK_rw81rfpusie5whmat7b381wd2 foreign key (FC_FEES_PARTICULAR_ID) references SMS_MA_FEES_PARTICULAR;
alter table SMS_TR_STUDENT_FEES add constraint FK_jxswf4fqsos13orakc7lb0el6 foreign key (SF_STUDENT_ID) references SMS_TR_STUDENT;
alter table SMS_TR_STUDENT_SCHOLARSHIP add constraint FK_2ephb77r7hcrdanu47bkfakss foreign key (STS_ADDRESS_ID) references SMS_TR_ADDRESS;
alter table SMS_TR_STUDENT_SCHOLARSHIP add constraint FK_8jcmj0vuomh0dxb7heltfi310 foreign key (STS_BRANCH_ID) references SMS_MA_BRANCH;
alter table SMS_TR_STUDENT_SCHOLARSHIP add constraint FK_9q75gmma55ww2cie0a19qgrel foreign key (STS_MARKETING_EMPLOYEE_ID) references SMS_TR_MARKETING_EMPLOYEE;
alter table SMS_TR_SUBJECT add constraint FK_d31sx5b8amslhcwb7sj81ed4e foreign key (SU_MD_ID) references SMS_TR_MARK_DETAILS;
create sequence hibernate_sequence;