-- user insertion
INSERT INTO SMS_MA_USER_ROLE(ID, UR_NAME, UR_DESC) VALUES (NULL, 'SUPER_ADMIN', 'Admin role');

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(NULL, 'branch', 'OPERATION' ,'branch pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(NULL, 1, 1);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(NULL, 'feesparticular', 'OPERATION' ,'feesparticular master pages related operations')
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(NULL, 1, 2);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(NULL, 'user','OPERATION' , 'user pages related operations')
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(NULL, 1, 3);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(NULL, 'course','OPERATION' , 'course pages related operations')
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(NULL, 1, 4);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(NULL, 'home','OPERATION' , 'home page related operations')
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(NULL, 1, 5);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(NULL, '/branch/**', 'URL' ,'branch pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(NULL, 1, 6);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(NULL, '/feesparticular/**', 'URL' ,'feesparticular master pages related operations')
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(NULL, 1, 7);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(NULL, '/user/**','URL' , 'user pages related operations')
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(NULL, 1, 8);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(NULL, '/course/**','URL' , 'course pages related operations')
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(NULL, 1, 9);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(NULL, '/role/**','URL' , 'role pages related operations')
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(NULL, 1, 10);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(NULL, 'student','OPERATION' , 'home page related operations')


INSERT INTO SMS_MA_USER (ID, US_FIRST_NAME, US_LAST_NAME, US_BRANCH, US_NAME, US_UR_ID, US_PASSWORD) VALUES (NULL, 'ADMIN', 'ADMIN', 'MMT01', 'ADMIN', 1, '$2a$10$IhHsRrddT9qVXke96pQqSO94hCzSlPolLHSElYFbKUaouVisr6g4W');

-- FEES_PARTICULAR INSERTION
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (NULL, 'FP001', 'Admission Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (NULL, 'FP002', 'Tution Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (NULL, 'FP003', 'Registration Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (NULL, 'FP004', 'Entrance Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (NULL, 'FP005', 'Uniform Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (NULL, 'FP006', 'Tamil/English Typing Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (NULL, 'FP007', 'Pratical/Lab Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (NULL, 'FP008', 'Book/Record Note Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (NULL, 'FP009', 'Exam Note Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (NULL, 'FP010', 'Hostel/Mess Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (NULL, 'FP011', 'Bus Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (NULL, 'FP012', 'Breakage Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (NULL, 'FP013', 'Other Fees');

--1.MELMARUVATHUR BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'MELMARUVATHUR', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 1, 'MMT01', 1, 'MELMARUVATHUR BRANCH');

--2.MADURANTHAGAM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'MADURANTHAGAM', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 2, 'MDT01', 1, 'MADURANTHAGAM BRANCH');

--3.CHENGALPATTU BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'CHENGALPATTU', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 3, 'CGP01', 1, 'CHENGALPATTU BRANCH');

--4.KANCHIPURAM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'KANCHIPURAM', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 4, 'KCP01', 1, 'KANCHIPURAM BRANCH');

--5.CHEYYAR BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'CHEYYAR', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 5, 'CHY01', 1, 'CHEYYAR BRANCH');

--6.ARANI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'ARANI', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 6, 'ARI01', 1, 'ARANI BRANCH');

--7.VELLORE BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'VELLORE', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 7, 'VLR01', 1, 'VELLORE BRANCH');

--8.CHETPATTU BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'CHETPATTU', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 8, 'CPT01', 1, 'CHETPATTU BRANCH');

--9.POLURE BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'POLURE', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 9, 'PLR01', 1, 'POLURE BRANCH');

--10.THIRUVANNAMALAI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'THIRUVANNAMALAI', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 10, 'TVM01', 1, 'THIRUVANNAMALAI BRANCH');

--11.GINGEE BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'GINGEE', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 11, 'GNE01', 1, 'GINGEE BRANCH');

--12.CHENGAM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'CHENGAM', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 12, 'CGM01', 1, 'CHENGAM BRANCH');

--13.THIRUVALLURE BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'THIRUVALLURE', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 13, 'TVR01', 1, 'THIRUVALLURE BRANCH');

--14.THIRUTHANI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'THIRUTHANI', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 14, 'TTN01', 1, 'THIRUTHANI BRANCH');

--15.ARAKKONAM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'ARAKKONAM', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 15, 'AKN01', 1, 'ARAKKONAM BRANCH');

--16.KALLAKURICHI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'KALLAKURICHI', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 16, 'KKI01', 1, 'KALLAKURICHI BRANCH');

--17.SANGARAPURAM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'SANGARAPURAM', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 17, 'SRP01', 1, 'SANGARAPURAM BRANCH');

--18.ULUNTHURPETTAI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'ULUNTHURPETTAI', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 18, 'UDP01', 1, 'ULUNTHURPETTAI BRANCH');

--19.VILLUPURAM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'VILLUPURAM', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 19, 'VPM01', 1, 'VILLUPURAM BRANCH');

--20.TINDIVANAM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'TINDIVANAM', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 20, 'TDM01', 1, 'TINDIVANAM BRANCH');

--21.CUDALURE BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'CUDALURE', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 21, 'CDL01', 1, 'CUDALURE BRANCH');

--22.CHIDAMBARAM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'CHIDAMBARAM', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 22, 'CDM01', 1, 'CHIDAMBARAM BRANCH');

--23.VANDAVASI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'VANDAVASI', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 23, 'VDV01', 1, 'VANDAVASI BRANCH');

--24.UTHIRAMERUR BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'UTHIRAMERUR', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 24, 'UMR01', 1, 'UTHIRAMERUR BRANCH');

--25.PRAMBALURE BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'PRAMBALURE', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 25, 'PBL01', 1, 'PRAMBALURE BRANCH');

--26.ARIYALURE BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'ARIYALURE', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 26, 'AYL01', 1, 'ARIYALURE BRANCH');

--27.TRICHY BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'TRICHY', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 27, 'TRY01', 1, 'TRICHY BRANCH');

--28.THANJAVUR BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'THANJAVUR', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 28, 'TJV01', 1, 'THANJAVUR BRANCH');

--29.PATTUKOTTAI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'PATTUKOTTAI', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 29, 'PTI01', 1, 'PATTUKOTTAI BRANCH');

--30.KUMBAKONAM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'KUMBAKONAM', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 30, 'KBM01', 1, 'KUMBAKONAM BRANCH');

--31.PUTHUKOTTAI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'PUTHUKOTTAI', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 31, 'PDI01', 1, 'PUTHUKOTTAI BRANCH');

--32.THURAIYUR BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'THURAIYUR', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 32, 'TRI01', 1, 'THURAIYUR BRANCH');

--33.MADURAI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'MADURAI', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 33, 'MDI01', 1, 'MADURAI BRANCH');

--34.NAMAKKAL BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'NAMAKKAL', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 34, 'NMK01', 1, 'NAMAKKAL BRANCH');

--35.VIRUTHUNAGAR BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'VIRUTHUNAGAR', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 35, 'VDN01', 1, 'VIRUTHUNAGAR BRANCH');

--36.SALEM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'SALEM', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 36, 'SLM01', 1, 'SALEM BRANCH');

--37.DINDUKAL BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'DINDUKAL', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 37, 'DDK01', 1, 'DINDUKAL BRANCH');

--38.DHARMAPURI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'DHARMAPURI', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 38, 'DMP01', 1, 'DHARMAPURI BRANCH');

--39.HARUR BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_CITY, AD_COUNTRY, AD_DOOR_NUMBER, AD_POSTAL_CODE, AD_STATE, AD_STREET_NAME) VALUES (NULL, 'HARUR', 'INDIA', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (NULL, 39, 'HRR01', 1, 'HARUR BRANCH');
