-- user insertion
INSERT INTO SMS_MA_USER_ROLE(ID, UR_NAME, UR_DESC) VALUES (nextval('SMS_SQ_UR'), 'SUPER_ADMIN', 'Admin role');

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'branch', 'OPERATION' ,'branch pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 1);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/branch/**', 'URL' ,'branch pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 2);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'feesparticular', 'OPERATION' ,'feesparticular master pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 3);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/feesparticular/**', 'URL' ,'feesparticular master pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 4);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'user','OPERATION' , 'user pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 5);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/user/**','URL' , 'user pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 6);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'course','OPERATION' , 'course pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 7);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/course/**','URL' , 'course pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 8);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'home','OPERATION' , 'home page related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 9);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/role/**','URL' , 'role pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 10);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'role','OPERATION' , 'marketing Employee page related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 11);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'student','OPERATION' , 'student page related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 12);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/student/**','URL' , 'student pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 13);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'marketingemployee','OPERATION' , 'marketing Employee page related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 14);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/marketingemployee/**','URL' , 'marketing Employee page related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 15);


INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'scheme','OPERATION' , 'marketing Employee page related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 16);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/scheme/**','URL' , 'marketing Employee page related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 17);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'securedoperation','OPERATION' , 'marketing Employee page related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 18);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/securedoperation/**','URL' , 'marketing Employee page related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 19);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'roleoperationlink','OPERATION' , 'marketing Employee page related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 20);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/roleoperationlink/**','URL' , 'marketing Employee page related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 21);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'idcard','OPERATION' , 'idcard page related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 22);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/idcard/**','URL' , 'idcard url related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 23);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'scholarshipenrollment','OPERATION' , 'scholarshipenrollment page related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 24);
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/scholarshipenrollment/**','URL' , 'scholarshipenrollment url related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 25);


INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'hotel', 'OPERATION' ,'hotel pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 26);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/hotel/**', 'URL' ,'hotel pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 27);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'hotelHr', 'OPERATION' ,'hotel hr pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 28);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/hotelhr/**', 'URL' ,'hotel hr pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 29);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'hoteltracker', 'OPERATION' ,'hotel tracker pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 30);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/hoteltracker/**', 'URL' ,'hotel tracker pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 31);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'messageservice', 'OPERATION' ,'message service pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 32);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/messageservice/**', 'URL' ,'message service pages related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 33);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'branchCreation', 'OPERATION' ,'create new Branch');
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'branchEdit', 'OPERATION' ,'Branch Edit');
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'branchDelete', 'OPERATION' ,'Branch Delete');
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'marketingEmployeeCreation', 'OPERATION' ,'Marketing Employee Creation');

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'marketingEmployeeEdit', 'OPERATION' ,'Marketing Employee Edit');
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'marketingEmployeeDelete', 'OPERATION' ,'Marketing Employee Delete');
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'courseCreation', 'OPERATION' ,'Course Creation');
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'courseEdit', 'OPERATION' ,'Course Edit');

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'courseDelete', 'OPERATION' ,'Course Delete');
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'feesparticularCreation', 'OPERATION' ,'Fees Particular Creation');
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'feesparticularEdit', 'OPERATION' ,'Fees Particular Edit');
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'feesparticularDelete', 'OPERATION' ,'Fees Particular Delete');

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'schemeCreation', 'OPERATION' ,'Scheme Creation');
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'schemeEdit', 'OPERATION' ,'Scheme Edit');
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'schemeDelete', 'OPERATION' ,'Scheme Delete');
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'studentCreation', 'OPERATION' ,'Student Creation');


INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'hotelCreation', 'OPERATION' ,'Hotel Creation');
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'hotelEdit', 'OPERATION' ,'Hotel Edit');
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'hotelHrCreation', 'OPERATION' ,'Hotel Hr Creation');
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'hotelHrEdit', 'OPERATION' ,'Hotel Hr Edit');


INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'hoteltrackerCreation', 'OPERATION' ,'Hotel Tracker Creation');
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'hoteltrackerEdit', 'OPERATION' ,'Hotel Tracker Edit');
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'makePayment', 'OPERATION' ,'Make Payment');
INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'manageDocument', 'OPERATION' ,'Manage Document');


INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/attendance/**','URL' , 'Attendance url related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 58);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/expense/**','URL' , 'Expense url related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 59);


INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/payment/**','URL' , 'Payment url related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 60);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/batch/**','URL' , 'Batch url related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 61);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'expenseCreation','OPERATION' , 'Expense Creation page related Operation');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 62);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'expenseEdit','OPERATION' , 'Expense Edit page related Operation');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 63);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'expenseDelete','OPERATION' , 'Expense Delete page related Operation');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 64);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'attendanceEdit','OPERATION' , 'Expense Delete page related Operation');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 65);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'attendanceMake','OPERATION' , 'Expense Delete page related Operation');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 66);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'batchCreation','OPERATION' , 'Batch Creation page related Operation');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 67);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'batchEdit','OPERATION' , 'Batch Edit page related Operation');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 68);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'batchDelete','OPERATION' , 'Batch Delete page related Operation');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 69);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'expense','OPERATION' , 'Batch Delete page related Operation');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 70);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'payment','OPERATION' , 'Batch Delete page related Operation');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 71);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'batch','OPERATION' , 'Batch Delete page related Operation');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 72);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'attendance','OPERATION' , 'Batch Delete page related Operation');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 73);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'scholarshipenrollmentEdit','OPERATION' , 'Scholarship edit related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 74);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'scholarshipenrollmentCreation','OPERATION' , 'Student Scholarship Creation');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 75);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'marketingCommissionCreation','OPERATION' , 'Marketing Commission Creation List');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 76);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'commissionDistributionList','OPERATION' , 'Marketing Commission Distribution List');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 77);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'marketingCommissionEdit','OPERATION' , 'Marketing Commisson Edit Operation');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 78);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), 'marketingCommission','OPERATION' , 'Marketing Commisson list operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 79);

INSERT INTO SMS_MA_SECURED_OPERATION(ID, SO_OPERATION, SO_TYPE, SO_OPERATION_DESC) VALUES(nextval('SMS_SQ_SO'), '/marketingCommission/**','URL' , 'Marketing Commisson url related operations');
INSERT INTO SMS_MA_ROLE_OPERATION_LINK(ID, ROL_UR_ID, ROL_SO_ID) VALUES(nextval('SMS_SQ_ROL'), 1, 80);

INSERT INTO SMS_MA_USER (ID, US_FIRST_NAME, US_LAST_NAME, US_BRANCH, US_NAME, US_UR_ID, US_PASSWORD) VALUES (nextval('SMS_SQ_US'), 'ADMIN', 'ADMIN', 'MMT01', 'ADMIN', 1, '$2a$10$IhHsRrddT9qVXke96pQqSO94hCzSlPolLHSElYFbKUaouVisr6g4W');

-- FEES_PARTICULAR INSERTION
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (nextval('SMS_SQ_FP'), 'FP001', 'Admission Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (nextval('SMS_SQ_FP'), 'FP002', 'Tution Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (nextval('SMS_SQ_FP'), 'FP003', 'Registration Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (nextval('SMS_SQ_FP'), 'FP004', 'Entrance Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (nextval('SMS_SQ_FP'), 'FP005', 'Uniform Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (nextval('SMS_SQ_FP'), 'FP006', 'Tamil/English Typing Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (nextval('SMS_SQ_FP'), 'FP007', 'Pratical/Lab Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (nextval('SMS_SQ_FP'), 'FP008', 'Book/Record Note Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (nextval('SMS_SQ_FP'), 'FP009', 'Exam Note Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (nextval('SMS_SQ_FP'), 'FP010', 'Hostel/Mess Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (nextval('SMS_SQ_FP'), 'FP011', 'Bus Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (nextval('SMS_SQ_FP'), 'FP012', 'Breakage Fees');
INSERT INTO SMS_MA_FEES_PARTICULAR (ID, FP_CODE, FP_NAME) VALUES (nextval('SMS_SQ_FP'), 'FP013', 'Other Fees');

--1.MELMARUVATHUR BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'MELMARUVATHUR', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 1, 'MMT01', 1, 'MELMARUVATHUR BRANCH');

--2.MADURANTHAGAM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'MADURANTHAGAM', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 2, 'MDT01', 1, 'MADURANTHAGAM BRANCH');

--3.CHENGALPATTU BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'CHENGALPATTU', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 3, 'CGP01', 1, 'CHENGALPATTU BRANCH');

--4.KANCHIPURAM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'KANCHIPURAM', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 4, 'KCP01', 1, 'KANCHIPURAM BRANCH');

--5.CHEYYAR BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'CHEYYAR', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 5, 'CHY01', 1, 'CHEYYAR BRANCH');

--6.ARANI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'ARANI', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 6, 'ARI01', 1, 'ARANI BRANCH');

--7.VELLORE BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'VELLORE', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 7, 'VLR01', 1, 'VELLORE BRANCH');

--8.CHETPATTU BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'CHETPATTU', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 8, 'CPT01', 1, 'CHETPATTU BRANCH');

--9.POLURE BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'POLURE', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 9, 'PLR01', 1, 'POLURE BRANCH');

--10.THIRUVANNAMALAI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'THIRUVANNAMALAI', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 10, 'TVM01', 1, 'THIRUVANNAMALAI BRANCH');

--11.GINGEE BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'GINGEE', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 11, 'GNE01', 1, 'GINGEE BRANCH');

--12.CHENGAM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'CHENGAM', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 12, 'CGM01', 1, 'CHENGAM BRANCH');

--13.THIRUVALLURE BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'THIRUVALLURE', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 13, 'TVR01', 1, 'THIRUVALLURE BRANCH');

--14.THIRUTHANI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'THIRUTHANI', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 14, 'TTN01', 1, 'THIRUTHANI BRANCH');

--15.ARAKKONAM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'ARAKKONAM', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 15, 'AKN01', 1, 'ARAKKONAM BRANCH');

--16.KALLAKURICHI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'KALLAKURICHI', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 16, 'KKI01', 1, 'KALLAKURICHI BRANCH');

--17.SANGARAPURAM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'SANGARAPURAM', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 17, 'SRP01', 1, 'SANGARAPURAM BRANCH');

--18.ULUNTHURPETTAI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'ULUNTHURPETTAI', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 18, 'UDP01', 1, 'ULUNTHURPETTAI BRANCH');

--19.VILLUPURAM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'VILLUPURAM', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 19, 'VPM01', 1, 'VILLUPURAM BRANCH');

--20.TINDIVANAM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'TINDIVANAM', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 20, 'TDM01', 1, 'TINDIVANAM BRANCH');

--21.CUDALURE BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'CUDALURE', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 21, 'CDL01', 1, 'CUDALURE BRANCH');

--22.CHIDAMBARAM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'CHIDAMBARAM', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 22, 'CDM01', 1, 'CHIDAMBARAM BRANCH');

--23.VANDAVASI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'VANDAVASI', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 23, 'VDV01', 1, 'VANDAVASI BRANCH');

--24.UTHIRAMERUR BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'UTHIRAMERUR', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 24, 'UMR01', 1, 'UTHIRAMERUR BRANCH');

--25.PRAMBALURE BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'PRAMBALURE', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 25, 'PBL01', 1, 'PRAMBALURE BRANCH');

--26.ARIYALURE BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'ARIYALURE', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 26, 'AYL01', 1, 'ARIYALURE BRANCH');

--27.TRICHY BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'TRICHY', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 27, 'TRY01', 1, 'TRICHY BRANCH');

--28.THANJAVUR BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'THANJAVUR', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 28, 'TJV01', 1, 'THANJAVUR BRANCH');

--29.PATTUKOTTAI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'PATTUKOTTAI', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 29, 'PTI01', 1, 'PATTUKOTTAI BRANCH');

--30.KUMBAKONAM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'KUMBAKONAM', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 30, 'KBM01', 1, 'KUMBAKONAM BRANCH');

--31.PUTHUKOTTAI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'PUTHUKOTTAI', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 31, 'PDI01', 1, 'PUTHUKOTTAI BRANCH');

--32.THURAIYUR BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'THURAIYUR', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 32, 'TRI01', 1, 'THURAIYUR BRANCH');

--33.MADURAI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'MADURAI', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 33, 'MDI01', 1, 'MADURAI BRANCH');

--34.NAMAKKAL BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'NAMAKKAL', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 34, 'NMK01', 1, 'NAMAKKAL BRANCH');

--35.VIRUTHUNAGAR BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'VIRUTHUNAGAR', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 35, 'VDN01', 1, 'VIRUTHUNAGAR BRANCH');

--36.SALEM BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'SALEM', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 36, 'SLM01', 1, 'SALEM BRANCH');

--37.DINDUKAL BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'DINDUKAL', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 37, 'DDK01', 1, 'DINDUKAL BRANCH');

--38.DHARMAPURI BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'DHARMAPURI', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 38, 'DMP01', 1, 'DHARMAPURI BRANCH');

--39.HARUR BRANCH
INSERT INTO SMS_TR_ADDRESS (ID, AD_TALUK,  AD_ADDRESS_1, AD_POSTAL_CODE, AD_DISTRICT, AD_ADDRESS_2) VALUES(nextval('SMS_SQ_AD'), 'HARUR', '1', '600063', 'TAMIL NADU', 'GANDHI NAGAR');
INSERT INTO SMS_MA_BRANCH (ID, BR_ADDRESS_ID, BR_CODE, BR_ACTIVE, BR_NAME) VALUES (nextval('SMS_SQ_BR'), 39, 'HRR01', 1, 'HARUR BRANCH');

--Welcome Message
INSERT into SMS_WELCOME_MESSAGE(id,sms_code,sms_message) values ('1','SMS_EMP_SCH','மாணவரின்  கல்வி உதவி தொகை படிவம் ஏற்றுக்கொள்ளப்பட்டது.');
INSERT into SMS_WELCOME_MESSAGE(id,sms_code,sms_message) values ('2','SMS_PRT_SCH','RGMIHM-ல்  இணைந்தமைக்கு வாழ்த்துக்கள்.');
INSERT into SMS_WELCOME_MESSAGE(id,sms_code,sms_message) values ('3','SMS_STD_SCH','RGMIHM-ல்  இணைந்தமைக்கு வாழ்த்துக்கள்.');
INSERT into SMS_WELCOME_MESSAGE(id,sms_code,sms_message) values ('4','SMS_PRT_STD','RGMIHM-ல்  இணைந்தமைக்கு வாழ்த்துக்கள்.');
INSERT into SMS_WELCOME_MESSAGE(id,sms_code,sms_message) values ('5','SMS_STD_STD','RGMIHM-ல்  இணைந்தமைக்கு வாழ்த்துக்கள்.');
INSERT into SMS_WELCOME_MESSAGE(id,sms_code,sms_message) values ('6','SMS_EMP_STD','மாணவரின்  கல்வி உதவி தொகை படிவம் ஏற்றுக்கொள்ளப்பட்டது.');
INSERT into SMS_WELCOME_MESSAGE(id,sms_code,sms_message) values ('7','SMS_STD_EXP','தங்கள் கல்வி உதவித்தொகை படிவம் காலவதி ஆகிவிட்டது, எனவே தாங்கள் புதிய  கல்வி உதவித்தொகை படிவத்தை   பெற்றுக்கொளவும். நன்றி.');
INSERT into SMS_WELCOME_MESSAGE(id,sms_code,sms_message) values ('8','SMS_PRT_EXP','தங்கள் மகன் / மகள் கல்வி உதவித்தொகை படிவம் காலவதி ஆகிவிட்டது, எனவே தாங்கள் புதிய  கல்வி உதவித்தொகை படிவத்தை பெற்றுக்கொளவும்.நன்றி.');
INSERT into SMS_WELCOME_MESSAGE(id,sms_code,sms_message) values ('9','SMS_EMP_EXP','தங்கள் பூர்த்தி செய்த கல்வி உதவித்தொகை படிவம் காலவதி ஆகிவிட்டது, எனவே தாங்கள் தக்க நடவடிக்கை மேற்கொள்ளுமாறு கேட்டுக்கொள்ளபடுகிறது. நன்றி.');
INSERT into SMS_WELCOME_MESSAGE(id,sms_code,sms_message) values ('10','SMS_STD_ABT','தாங்கள் எந்தவொரு முன் அறிவிப்பின்றி விடுமுறை எடுத்துள்ளீர்கள். எனவே தங்கள் பெற்றோரை அழைத்து வரவும். நன்றி.');
INSERT into SMS_WELCOME_MESSAGE(id,sms_code,sms_message) values ('11','SMS_PRT_ABT','தங்கள் மகன் / மகள் எந்தவொரு முன் அறிவிப்பின்றி விடுமுறை எடுத்துள்ளார். எனவே தாங்கள் கல்லூரியை தொடர்பு கொள்ளவும். நன்றி');
INSERT into SMS_WELCOME_MESSAGE(id,sms_code,sms_message) values ('12','SMS_EMP_ABT','இவர் எந்தவொரு முன் அறிவிப்பின்றி விடுமுறை எடுத்துள்ளார் . எனவே இவரை தொடர்பு கொள்ளவும். நன்றி.');
INSERT into SMS_WELCOME_MESSAGE(id,sms_code,sms_message) values ('13','SMS_STD_ALV','தங்கள் விடுமுறை இன்று அனுமதிக்கப்பட்டது நன்றி');
INSERT into SMS_WELCOME_MESSAGE(id,sms_code,sms_message) values ('14','SMS_PRT_ALV','தங்கள் மகன் / மகள்  இன்று கல்லூரி அனுமதியுடன் விடுமுறை எடுத்துள்ளார்.நன்றி.');

